Class {
	#name : #CSNSNullWidget,
	#superclass : #CSNWidget,
	#category : #'Casino-Model-Silverlight-Entities'
}

{ #category : #meta }
CSNSNullWidget class >> annotation [

	<MSEClass: #NullWidget super: #CSNWidget>
	<package: #'Casino-Model-Silverlight'>
	<generated>
	^self
]

{ #category : #generator }
CSNSNullWidget class >> generatedSlotNames [
	<generated>
	'CSNSNullWidget class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNSNullWidget class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNSNullWidget class >> requirements [

	<generated>
	^ {  }
]
